# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: My sample book
author: Soeren Thomesn
logo: logo.jpg

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib
